name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x.x

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get project name and version
        id: pkginfo
        shell: bash
        run: |
          NAME=$(node -e "console.log(require('./package.json').name)")
          VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if Tag Exists
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/v${{ steps.pkginfo.outputs.version }}$"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pkginfo.outputs.name }}_v${{ steps.pkginfo.outputs.version }}_${{ matrix.os }}
          path: release/
          retention-days: 5

      - name: Create Release
        id: create_release
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.pkginfo.outputs.version }}
          name: ${{ steps.pkginfo.outputs.name }} v${{ steps.pkginfo.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip Release Files (Linux/macOS)
        if: runner.os != 'Windows' && steps.check_tag.outputs.exists == 'false'
        run: |
          zip -r ${{ steps.pkginfo.outputs.name }}_v${{ steps.pkginfo.outputs.version }}_${{ matrix.os }}.zip ./release/*
        shell: bash

      - name: Zip Release Files (Windows)
        if: runner.os == 'Windows' && steps.check_tag.outputs.exists == 'false'
        run: |
          Compress-Archive -Path release/* -DestinationPath "${{ steps.pkginfo.outputs.name }}_v${{ steps.pkginfo.outputs.version }}_${{ matrix.os }}.zip"
        shell: pwsh

      - name: Upload Release Asset
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.pkginfo.outputs.name }}_v${{ steps.pkginfo.outputs.version }}_${{ matrix.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}