name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies
        run: npm install

      # - name: Run Tests
      #   run: npm test
      #   continue-on-error: true

      - name: Build Release Files
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get project name and version
        id: pkginfo
        shell: bash
        run: |
          NAME=$(node -e "console.log(require('./package.json').name)")
          VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if Tag Exists
        id: check_tag
        shell: bash
        run: |
          TAG_EXISTS=$(git tag -l "v${{ steps.pkginfo.outputs.version }}")
          if [ -n "$TAG_EXISTS" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.pkginfo.outputs.name }}_v${{ steps.pkginfo.outputs.version }}_${{ matrix.os }}
          path: release/
          retention-days: 5

      - name: Zip Release Files (Linux/macOS)
        if: runner.os != 'Windows' && steps.check_tag.outputs.exists == 'false'
        run: |
          if [ -d "release" ] && [ "$(ls -A release)" ]; then
            zip -r ${{ steps.pkginfo.outputs.name }}_v${{ steps.pkginfo.outputs.version }}_${{ matrix.os }}.zip ./release/*
          else
            echo "No files to zip."
          fi
        shell: bash

      - name: Zip Release Files (Windows)
        if: runner.os == 'Windows' && steps.check_tag.outputs.exists == 'false'
        run: |
          if (Test-Path release -PathType Container -and (Get-ChildItem release)) {
            Compress-Archive -Path release/* -DestinationPath "${{ steps.pkginfo.outputs.name }}_v${{ steps.pkginfo.outputs.version }}_${{ matrix.os }}.zip"
          } else {
            Write-Host "No files to zip."
          }
        shell: pwsh

      - name: Create Release and Upload Asset
        if: steps.check_tag.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.pkginfo.outputs.version }}
          name: ${{ steps.pkginfo.outputs.name }} v${{ steps.pkginfo.outputs.version }}
          draft: false
          prerelease: false
          files: ${{ steps.pkginfo.outputs.name }}_v${{ steps.pkginfo.outputs.version }}_${{ matrix.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}